### ISSUE TITLE
如何配置自定义告警信息

### ISSUE THREAD

**Issue by test98123456** [anjia0532/elastalert-wechat-plugin#12]
在使用elastalert时，本想使用HTTP POST发送告警，但是想发送自定义内容，无果，转而看到您这个仓库，也没又找到，发送的内容是个matches，如何自定义内容呢？谢谢~

**Comment by anjia0532** [comment]
我这个只是把内容发到微信公众号，其实官方是支持自定义内容的，不过很弱。是基于python的format

**Comment by anjia0532** [comment]
https://elastalert.readthedocs.io/en/latest/ruletypes.html#alert-content

**Comment by test98123456** [comment]
是挺弱的，alert_text还用不了，还有个bug，[issue](https://github.com/Yelp/elastalert/issues/2083)

**Comment by anjia0532** [comment]
这是我用的。
```yaml
alert_text_type: alert_text_only
alert_text: |
  心跳报警
  时间: {}
  接口: {}
  类型: {}
  状态: {}
  耗时: {}
  ip: {}
  port: {}
  url: {}
alert_text_args:
  - "@timestamp"
  - fields.module
  - monitor.type
  - monitor.status
  - monitor.duration.us
  - monitor.ip
  - tcp.port
  - http.url
```
